# Generated by Django 3.1.6 on 2021-02-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='account/images/'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='resume_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
