# Generated by Django 3.1.6 on 2021-02-05 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(max_length=255)),
                ('appIcon', models.ImageField(upload_to='app/images/icons')),
                ('gitlink', models.TextField(blank=True, null=True)),
                ('videolink', models.TextField(blank=True, null=True)),
                ('playstorelink', models.TextField(blank=True, null=True)),
                ('appstorelink', models.TextField(blank=True, null=True)),
                ('weblink', models.TextField(blank=True, null=True)),
                ('images', models.ImageField(upload_to='app/images/$<django.db.models.fields.CharField>/snaps')),
                ('headers', models.CharField(max_length=255)),
                ('header_infos', models.CharField(max_length=255)),
                ('likes', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
