# Generated by Django 3.1.6 on 2021-02-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='images',
            field=models.ImageField(upload_to='app/images/appdata/snaps'),
        ),
    ]
